### PR TITLE
adding twig components from drupal starterkit

### PR DESCRIPTION
**Pull request by EvanLovely**
@aleksip So what do we think about adding the `_twig-components` folder in here? After running the starterkit install process it asks if we want to merge or replace, we could chose merge and then get the combined source folder of our chosen starterkit and the Drupal Twig Components needed.

### CODE REVIEW

**Comment by aleksip** [comment]
Wow, haven't tested it but if this works it seems like a great stopgap solution while waiting for a `Twig_ExtensionInterface` based one!

**Comment by aleksip** [comment]
If we do this, there isn't really anything Drupal specific left in `starterkit-twig-drupal-minimal`. Should we then default to `starterkit-twig-base` or add some Drupal examples to `_patterns`?

**Comment by EvanLovely** [comment]
Probably add some Drupal examples in. Perhaps add a new starterkit for a demo: `starterkit-twig-drupal-demo` as that convention is for examples and the "minimal" / "base" seems to be just the folder scaffolding and a few files and a super basic demo / compile test.

**Comment by EvanLovely** [comment]
@dmolsen Is there any other way you know of to add Twig Components (filters, functions, etc) besides in StarterKits in `source/_twig-components/`? Perhaps a plugin? It would be great for this Drupal Edition to require those so that way long running projects can get updates and fixes to them. If not, that's ok; just curious before we go down the above route further. Thanks!

**Comment by dmolsen** [comment]
@EvanLovely -

The Pattern Lab `InstallerUtil` is pretty flexible. You can use the installer to move files to almost anywhere in the system. I think you could tackle this this way:

1. Create a repo or repos for components.
2. Create a folder called `dist/` in the repo (this is a hard requirement)
3. Put components in it
4. Add a `composer.json` file with the the `"extra": { "patternlab": { "dist": { "sourceDir": [] } } }` bit [like this one](https://github.com/pattern-lab/styleguidekit-assets-default/blob/6825b008795ce7c5f8774e584ae1f67422dbb88d/composer.json#L29-L50). That will move the appropriate files from `dist/` to wherever a user has determined the source dir to be (usually `source/`). Review the [rules for moving files](https://github.com/pattern-lab/patternlab-php-core/blob/725f3730ec4051a50cd73530e9916fa38cfa5558/src/PatternLab/InstallerUtil.php#L88-L93).
5. Add a `type` to your `composer.json`. You can [choose from these](https://github.com/pattern-lab/unified-asset-installer). "patternlab-plugin" is probably appropriate. We can always come up with another type if we need to.

Make sense? I think the primary issue as always is install order.

**Comment by EvanLovely** [comment]
@dmolsen Great!! Could you make that repo for us? Perhaps named `plugin-drupal-twig-components`? Feel free to pick whatever sounds good; we basically just want a single place for those instead of them in each StarterKit. 

I can get the files in there, but if you're feeling it, you can [grab this tarball](https://github.com/pattern-lab/starterkit-twig-drupal-minimal/archive/master.zip) and pull the `dist/_twig-components/` folder in. Thanks Dave! I think this is a much better approach!

**Comment by EvanLovely** [comment]
@aleksip We've got a repo for a new "Demo" StarterKit for Drupal: pattern-lab/starterkit-twig-drupal-demo that's a straight copy of the minimal version. I've got an issue to make it cool and demo how it can be used: pattern-lab/starterkit-twig-drupal-demo#1

**Comment by dmolsen** [comment]
@EvanLovely -

I did a barebones set-up of this.

* [Github repo](https://github.com/pattern-lab/plugin-drupal-twig-components)
* [Packagist entry](https://packagist.org/packages/pattern-lab/drupal-twig-components)

Things to consider:

1. Modify `LICENSE` as appropriate. If it needs to be GPL that's fine. Just update for you and/or Aleksi's info. I copied in one that has my info.
2. Create a `dev` branch
3. Make a `v1.0.0` tag when you're ready. I just did `v0.1.1` to test Packagist.
4. Try installing it. Worked for me though it says "you have stuff in these directories." I assume that won't be the case if you pull it from the StarterKit proper.

I was overly specific when setting up the `sourceDir` mappings. Probably could have gotten away with `*`: `_twig-components/*`. Let me know if either of you have questions.

**Comment by EvanLovely** [comment]
@dmolsen : **AWESOME**

OK, I've begun working in the branch `feature/drupal-twig-components-dep` by running `composer require pattern-lab/drupal-twig-components` and successfully seeing them install and copy from packages into the default `source/_twig-components/` directory! :) I even made a micro-release of [`v0.1.2`](https://github.com/pattern-lab/plugin-drupal-twig-components/releases/tag/v0.1.2) and saw `composer update` bring in the changes!

So we've got a good, successful, updatable install right of the bat!! Thanks!!

I've got a PR up for it over in PR #10 ! Closing this PR down now – let's continue the discussion over there.

**Comment by dmolsen** [comment]
Nice to see all of the `InstallerUtil` work pay off and address a real world need :)

**Pull request closed without merging**
