### PR TITLE
basic docs

### LINKED ISSUE #6: Add documentation to get started
Show how someone could get this up and running.

**Things to add**

- [ ] Config file changes - needed while we wait on https://github.com/pattern-lab/patternlab-php-core/issues/15

### PR DESCRIPTION
**Pull request by EvanLovely**
This resolves #6 - @aleksip Can you take a look and see what you think? There's also a need to get some docs or changes to the script so that once someone sets up the repo and commits the starterkit and config and then others clone the site and run `composer install` they get asked to replace the config; we don't want that. Thoughts?

### CODE REVIEW

**Comment by aleksip** [comment]
Docs and `.gitignore` changes look good, but do we need to add `config.yml`? It gets added by `composer install` and could change if there are changes in `patternlab-php-core` or `patternengine-php-twig`.

**Comment by aleksip** [comment]
It looks like config changes won't be prompted for or replaced if the `overrideConfig` option is set to `false` (or something other than `q` or `a`). But I guess we could ask for a comment from @dmolsen on how to best handle this.

If we were to add `config.yml` with `overrideConfig: false` we could always set `twigDebug` to `false` as well and get rid of that extra step!

**Comment by EvanLovely** [comment]
OK @aleksip I've done the changes you just suggested in 8e3bd76 

I like the idea of having as much config and tweaking done automatically as possible so this "just works" for people.

**Comment by dmolsen** [comment]
A better option probably would be to get editions to support setting config options and setting that to silently override the defaults found in core. If we set `config.yml` to never allow updates then future updates to core or other packages that need to set a new config option won't work. Will need to parse the flow of composer events to see where that should fall.

**Comment by EvanLovely** [comment]
@dmolsen ok, I've unset the `overrideConfig` changes back to what it was before. How would we do what you suggested?

**Comment by EvanLovely** [comment]
Per our chat conversation, I've moved `overrideConfig` back to false.

**Pull request merged**
